version: '3.4'

networks:
  postgres-dev:
    driver: bridge

services:
  trading.analytics.monitoring:
    image: ${DOCKER_REGISTRY-}tradinganalyticsmonitoring
    build:
      context: .
      dockerfile: src/Trading.Analytics.Monitoring/Dockerfile

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /data/
    volumes:
       - postgres:/data/
    ports:
      - "54321:5432"
    networks:
      - postgres-dev
    restart: unless-stopped
    command:
      - "postgres"
      - "-c"
      - "max_prepared_transactions=100"
    
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-postgres@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5151}:80"
    networks:
      - postgres-dev
    restart: unless-stopped

volumes:
    postgres:
    pgadmin:
